# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3061f94c915b200cdc029053bbae536f18c4011d94690d3706275ad24b68e9613ee1bc77ba19c0d59046439635ec9db7f924a911eb68b15a324c62c792ea8d25

test:
  secret_key_base: 0088107493c93b183565fbb25a9207a022cf3cfb7e0a1a2b3ef6fce6a286b80e75d0f35d49314d4add71bb07c6259742324facc426381db71e482ea69612a5d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
